# Domain layer = the business logic for a feature, plus the SQL that backs it.
#
# The rule that shapes this file: it does NOT import fastapi. Nothing here knows
# what an HTTP status code is. When a draft can't be found, this returns None —
# it is the API layer's job to decide that None means "404". That separation is
# what lets the same function be called later from a background job, a CLI
# script, or a test, none of which have a request or a response to work with.

import logging

from src.integrations.db import db

logger = logging.getLogger(__name__)


def create_draft() -> dict:
    """Start a new anonymous onboarding draft.

    Called before the user has an account — they haven't even reached the
    signup screen yet. Every column is left at its database default, which is
    the point: `id` and `token` are both generated by Postgres.

    The returned `token` is the only thing that will ever prove ownership of
    this draft, since there is no logged-in user to check against. The browser
    stores it and sends it back as the X-Draft-Token header on every update.
    """
    with db() as conn, conn.cursor() as cur:
        cur.execute("INSERT INTO memoir_draft DEFAULT VALUES RETURNING id, token")
        row = cur.fetchone()
    return {"id": row["id"], "token": row["token"]}


def update_draft(draft_id: str, token: str, fields: dict) -> dict | None:
    """Save one or more onboarding answers onto an existing draft.

    `fields` is a plain dict of column name -> value, already filtered down to
    just what the client actually sent. Note the type: a dict, not a pydantic
    model. Converting the model into a dict happens up in the API layer, so
    this function doesn't need to know that pydantic exists.

    Returns the updated row, or None if nothing matched.

    That None covers three different situations on purpose:
      - no draft with that id
      - a draft with that id, but the wrong token
      - a draft that has already been claimed into a real memoir

    The caller cannot tell which. That is deliberate — telling an attacker
    "that id exists, your token is wrong" hands them half the answer.
    """
    # Build the SET clause from the field names the client sent.
    #
    # This is an f-string in SQL, which normally means an injection hole. It is
    # safe here for two reasons. First, only column NAMES go in this way, and
    # SQL has no way to bind a column name as a parameter — it has to be part
    # of the statement text. Second, those names cannot be attacker-controlled:
    # they are the keys of a dict produced by a pydantic model, which silently
    # drops any field it doesn't declare.
    #
    # Every VALUE still goes through a %(name)s placeholder and is passed to
    # psycopg separately, which is the part that actually prevents injection.
    sets = ", ".join(f"{name} = %({name})s" for name in fields)

    params = dict(fields)
    params["draft_id"] = draft_id
    params["token"] = token

    with db() as conn, conn.cursor() as cur:
        cur.execute(
            f"""
            UPDATE memoir_draft
               SET {sets}, updated_at = now()
             WHERE id = %(draft_id)s
               AND token = %(token)s
               AND claimed_at IS NULL
         RETURNING id, subject_name, relationship, relationship_label,
                   born_year, through_year, subject_is_living, never_forget
            """,
            params,
        )
        row = cur.fetchone()

    # Already None when the WHERE matched nothing, so there is nothing to check.
    return row
